name: saic_ismart_example
description: Example Flutter app for the saic_ismart package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  saic_ismart:
    path: ../

flutter:
  uses-material-design: true
